print("hello project")
print("***********I AM RIYA SONI **********")
from turtle import *
import time
time.time()
t=Turtle()
wn=Screen()
wn.title("Simple analog clock")
wn.bgcolor("black")
wn.setup(600,600)
t.speed(1)
t.pensize(3)
t.hideturtle()
wn.tracer(0)
def draw_clock(h,m,s,t):
    t.penup()
    t.goto(0,210)
    t.setheading(180)
    t.pencolor("pink")
    t.pendown()
    t.circle(210)
    #("draw the clock  marking for hand hours")
    t.penup()
    t.goto(0,0)
    t.setheading(90)
    for i in range(12):
        t.forward(180)
        t.pendown()
        t.fd(30)
        t.penup()
        t.goto(0,0)
        t.right(30)
    #("clock marking for minute and second hour")
    t.penup()
    t.goto(0,0)
    t.setheading(90)
    for i in range(60):
        t.forward(200)
        t.pendown()
        t.fd(10)
        t.penup()
        t.goto(0,0)
        t.right(6)
    #("draw hour hand")
    t.penup()
    t.goto(0,0)
    t.setheading(90)
    t.pencolor("white")
    angle=(h/12)*360
    t.right(angle)
    t.pendown()
    t.fd(70)
    
    #("draw minute hand")
    t.penup()
    t.goto(0,0)
    t.pencolor("gold")
    t.setheading(90)
    angle=(m/60)*360
    t.right(angle)
    t.pendown()
    t.fd(120)
    
    #draw second hand
    t.penup()
    t.goto(0,0)
    t.pencolor("green")
    t.setheading(90)
    angle=(s/60)*360
    t.right(angle)
    t.pendown()
    t.fd(80)
    #designed by
    t.penup()
    t.goto(0,0)
    t.pencolor("silver")
    t.setheading(260)
    t.fd(120)
    t.setheading(0)
    t.fd(5)
    t.write("RIYA SONI" ,move=False ,align="center", font=("arial", 20 , "normal")) 
while True:
    h=int(time.strftime("%I"))
    m=int(time.strftime("%M"))
    s=int(time.strftime("%S"))
    draw_clock(h,m,s,t)
    wn.update()
    time.sleep(1)
    t.clear()
mainloop()


